# Generated by Django 3.2.7 on 2021-09-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_event_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='zipcode',
            field=models.CharField(max_length=6),
        ),
    ]
