# Generated by Django 3.2.7 on 2021-09-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210915_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='entry',
            field=models.CharField(blank=True, choices=[('paid', 'Bezahlt'), ('vip', 'Gästeliste')], default=None, max_length=4),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='proof',
            field=models.CharField(choices=[('tested', 'Getestet'), ('vaccinated', 'Geimpft'), ('recovered', 'Genesen')], default=None, max_length=10),
        ),
    ]
